name: Generate RSS Feed

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main ]
    paths-ignore:
      - 'rss.xml'
      - 'node_modules/**'

permissions:
  contents: write

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate RSS feed
      env:
        RAINDROP_TOKEN: ${{ secrets.RAINDROP_TOKEN }}
      run: npm run generate-rss
      
    - name: Check if RSS file was generated
      run: |
        if [ ! -f rss.xml ]; then
          echo "Error: RSS file was not generated"
          exit 1
        fi
        echo "RSS file generated successfully"
        ls -la rss.xml
      
    - name: Commit and push RSS file
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add rss.xml
        if git diff --staged --quiet; then
          echo "No changes to RSS file"
        else
          git commit -m "Update RSS feed - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push
          echo "RSS feed updated and pushed"
        fi 